In [8]:
import pandas as pd

df = pd.read_parquet('data/top100.parquet')
df.head()

   item_id  count  rank
0   461686    306     1
1   312728    162     2
2   409804    156     3
3   320130    141     4
4    29196    136     5

In [ ]:
df1 = pd.read_parquet('data/events_test.parquet')
df1.sample(10)

         user_id      event  item_id  transactionid                    date
775973    529460  addtocart   247755            NaN 2015-08-10 17:54:51.171
611157    367142       view   461610            NaN 2015-08-01 15:44:53.380
1097994  1224898       view   100282            NaN 2015-08-29 01:25:20.848
746924    171543       view   375738            NaN 2015-08-08 14:55:18.044
1072099   215754       view   138298            NaN 2015-08-26 15:56:13.598
818606     37732       view   301517            NaN 2015-08-12 21:37:53.970
796537    489034       view   242389            NaN 2015-08-11 20:42:07.077
828462    746242       view   463236            NaN 2015-08-13 20:29:51.655
1067672   821216       view   452628            NaN 2015-08-26 19:51:10.230
792047   1023658       view    52653            NaN 2015-08-11 23:42:25.405